# Generated by Django 5.1.3 on 2024-11-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_city_remove_user_subscribed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo Code')),
                ('duration', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year')], verbose_name='Duration (Months)')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Maximum Uses')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Current Uses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='users.subscriptionplan', verbose_name='Subscription Plan')),
            ],
        ),
    ]
