# Generated by Django 5.1.3 on 2024-11-22 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (None, 'Forever')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (None, 'Forever')], null=True, verbose_name='Duration (Months)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='bonus_modules',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='users.bonusmodule'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='users.programminglanguage'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (None, 'Forever')], default=1, verbose_name='Subscription Duration')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='users.subscriptionplan', verbose_name='Subscription Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
