# Generated by Django 5.1.3 on 2024-11-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bonusmodule_programminglanguage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='duration',
        ),
        migrations.AddField(
            model_name='promocode',
            name='bonus_modules',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='users.bonusmodule', verbose_name='Bonus Modules'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='users.programminglanguage', verbose_name='Programming Languages'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='users.subscriptionduration', verbose_name='Subscription Duration'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='users.subscriptionplanmodes', verbose_name='Subscription Plan Mode'),
        ),
    ]
