# Generated by Django 5.1.3 on 2024-11-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscriptionduration_subscriptionplanmodes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionDuration',
            new_name='SubscriptionDurationTypes',
        ),
    ]
