# Generated by Django 5.1.3 on 2024-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_subscriptionduration_subscriptiondurationtypes'),
    ]

    operations = [
    ]
