# Generated by Django 5.1.3 on 2024-11-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='bonus_modules',
            field=models.ManyToManyField(related_name='user_bonus_subscriptions', to='users.bonusmodule'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='programming_languages',
            field=models.ManyToManyField(related_name='user_prog_subscriptions', to='users.programminglanguage'),
        ),
    ]
