# Generated by Django 5.1.3 on 2024-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersubscription_bonus_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondurationtypes',
            name='value',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
