# Generated by Django 5.1.3 on 2024-11-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('users', '0012_subscriptionplan_end_date_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programming_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.programminglanguage'),
            preserve_default=False,
        ),
    ]
