# Generated by Django 5.1.3 on 2024-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_programming_language'),
        ('users', '0012_subscriptionplan_end_date_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='course',
            name='bonus_modules',
            field=models.ManyToManyField(related_name='courses', to='users.bonusmodule'),
        ),
        migrations.AddField(
            model_name='course',
            name='programming_languages',
            field=models.ManyToManyField(related_name='courses', to='users.programminglanguage'),
        ),
    ]
