# Generated by Django 5.1.3 on 2024-12-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lesson_options_lesson_description_lesson_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.lessontestresult')),
            ],
        ),
        migrations.DeleteModel(
            name='LessonTestQuestion',
        ),
    ]
