# Generated by Django 5.1.3 on 2024-12-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_homeworksubmissionstatuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_status', to='course.homeworksubmissionstatuses', verbose_name='Submission Status'),
        ),
    ]
