# Generated by Django 5.1.3 on 2024-12-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lesson_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
